Repository Rahix/avr-hal, pull requests merged in 2020-08, with the labels that each got.

#30 Add Arduino Mega 2560, ATmega2560
  Cargo.toml
  README.md
  boards/arduino-mega2560/.cargo/config.toml
  boards/arduino-mega2560/Cargo.toml
  boards/arduino-mega2560/avr-atmega2560.json
  boards/arduino-mega2560/examples/mega2560-adc.rs
  boards/arduino-mega2560/examples/mega2560-blink.rs
  boards/arduino-mega2560/examples/mega2560-i2cdetect.rs
  boards/arduino-mega2560/examples/mega2560-panic.rs
  boards/arduino-mega2560/examples/mega2560-serial.rs
  boards/arduino-mega2560/examples/mega2560-spi-feedback.rs
  boards/arduino-mega2560/src/lib.rs
  boards/arduino-mega2560/src/pins.rs
  chips/atmega2560-hal/Cargo.toml
  chips/atmega2560-hal/avr-atmega2560.json
  chips/atmega2560-hal/src/adc.rs
  chips/atmega2560-hal/src/lib.rs
  chips/atmega2560-hal/src/port.rs
  chips/atmega2560-hal/src/spi.rs
  chips/atmega2560-hal/src/usart.rs
Labels: mcu-support

#36 Added u8 ms delay
  avr-hal-generic/src/delay.rs
  boards/arduino-leonardo/examples/leonardo-adc.rs
  boards/arduino-leonardo/examples/leonardo-blink.rs
  boards/arduino-leonardo/examples/leonardo-i2cdetect.rs
  boards/arduino-leonardo/examples/leonardo-interrupt.rs
  boards/arduino-leonardo/examples/leonardo-spi-feedback.rs
  boards/arduino-mega2560/examples/mega2560-adc.rs
  boards/arduino-mega2560/examples/mega2560-blink.rs
  boards/arduino-mega2560/examples/mega2560-i2cdetect.rs
  boards/arduino-mega2560/examples/mega2560-spi-feedback.rs
  boards/arduino-uno/examples/uno-blink.rs
  boards/arduino-uno/examples/uno-i2cdetect.rs
  boards/arduino-uno/examples/uno-spi-feedback.rs
  boards/bigavr6/examples/bigavr6-blink.rs
  boards/bigavr6/examples/bigavr6-i2cdetect.rs
Labels: hal-impl

#48 spi: Fix F_osc/128 configuration
  avr-hal-generic/src/spi.rs
Labels: bug

#56 Single-instruction pin toggling.
  avr-hal-generic/src/port.rs
Labels: hal-impl

#50 Add base hal support for Atmega48P chip
  Cargo.toml
  chips/atmega48p-hal/Cargo.toml
  chips/atmega48p-hal/avr-atmega48p.json
  chips/atmega48p-hal/src/adc.rs
  chips/atmega48p-hal/src/lib.rs
  chips/atmega48p-hal/src/port.rs
  chips/atmega48p-hal/src/pwm.rs
  chips/atmega48p-hal/src/spi.rs
Labels: mcu-support

#65 Implemented Watchdog(En/Dis) for ATmega328P
  avr-hal-generic/src/lib.rs
  avr-hal-generic/src/wdt.rs
  boards/arduino-uno/examples/uno-watchdog.rs
  boards/arduino-uno/src/lib.rs
  chips/atmega328p-hal/src/lib.rs
  chips/atmega328p-hal/src/wdt.rs
Labels: hal-impl

#62 SparkFun Qwiic Pro Micro USB-C Atmega32u4
  .travis.yml
  Cargo.toml
  boards/sparkfun-pro-micro/.cargo/config.toml
  boards/sparkfun-pro-micro/Cargo.toml
  boards/sparkfun-pro-micro/avr-atmega32u4.json
  boards/sparkfun-pro-micro/examples/pro-micro-adc.rs
  boards/sparkfun-pro-micro/examples/pro-micro-blink.rs
  boards/sparkfun-pro-micro/examples/pro-micro-i2cdetect.rs
  boards/sparkfun-pro-micro/examples/pro-micro-interrupt.rs
  boards/sparkfun-pro-micro/examples/pro-micro-panic.rs
  boards/sparkfun-pro-micro/examples/pro-micro-pwm.rs
  boards/sparkfun-pro-micro/examples/pro-micro-serial.rs
  boards/sparkfun-pro-micro/examples/pro-micro-spi-feedback.rs
  boards/sparkfun-pro-micro/pro-micro-runner.sh
  boards/sparkfun-pro-micro/src/lib.rs
  boards/sparkfun-pro-micro/src/pins.rs
Labels: mcu-support
